### ISSUE TITLE
Can I convince you to put this on the AUR?

### ISSUE THREAD

**Issue by Frans-Willem** [qzed/libwacom-surface#1]
Hi,

This package works like a charm, but it took me a couple of days to actually find out it existed.
Could you put this on AUR ? I think it should be as easy as adding your public key to your AUR account, adding an extra remote, and git pushing what you have now :-/

**Comment by qzed** [comment]
I'll have a look at it!

**Comment by qzed** [comment]
Done: https://aur.archlinux.org/packages/libwacom-surface/

**Comment by Frans-Willem** [comment]
Thank you! :tada: :confetti_ball:
