### ISSUE TITLE
Stylus acts like eraser if tilted

### ISSUE THREAD

**Issue by ShapeShifter499** [qzed/libwacom-surface#2]
I found your package on AUR. It doesn't seem to help with the issues I'm experiencing. But I'm hoping you might be able to provide a fix.  On my Surface Go if I tilt the pen to far to the side while writing it switches to an eraser even though the pen side is still against the screen. 

I'm making use of @jakeday's kernel.

Related issues.
https://github.com/jakeday/linux-surface/issues/429

**Comment by ShapeShifter499** [comment]
Also related possiblity to a entirely different tablet I own. https://github.com/linuxwacom/libwacom/issues/70

**Comment by qzed** [comment]
I doubt there's anything I can do here. Libwacom only provides basic information related to the tablet, such as which devices are tablets, the number of buttons, and other features. This seems more driver-related. Let's continue this in the issue you linked.
